custom python compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -139,38 +139,56 @@ mkdir -p $(dirname $PROFILE_PATH)
 set +e
 PYTHON_VERSION=$(cat runtime.txt)
 
+# Compile Python
+curl -s https://static-6px.s3.amazonaws.com/archive/python-2.7.6.tar.gz > python-2.7.6.tar.gz
+tar zxf python-2.7.6.tar.gz
+cd python-2.7.6
+./configure --enable-shared | indent
+make | indent
+make install | indent
+cd ..
+
+mv python-2.7.6 .heroku/python
+
+# Record for future rference
+echo python-2.7.6 > .heroku/python-version
+FRESH_PYTHON=true
+
+echo "PYTHON COMPILE COMPLETE" | indent
+exit
+
 # Install Python
-if [ -f .heroku/python-version ]; then
-  if [ ! $(cat .heroku/python-version) = $PYTHON_VERSION ]; then
-    bpwatch start uninstall_python
-      puts-step "Found $(cat .heroku/python-version), removing."
-      rm -fr .heroku/python
-    bpwatch stop uninstall_python
-  else
-    SKIP_INSTALL=1
-  fi
-fi
+# if [ -f .heroku/python-version ]; then
+#   if [ ! $(cat .heroku/python-version) = $PYTHON_VERSION ]; then
+#     bpwatch start uninstall_python
+#       puts-step "Found $(cat .heroku/python-version), removing."
+#       rm -fr .heroku/python
+#     bpwatch stop uninstall_python
+#   else
+#     SKIP_INSTALL=1
+#   fi
+# fi
 
-if [ ! "$SKIP_INSTALL" ]; then
-  bpwatch start install_python
-    puts-step "Preparing Python runtime ($PYTHON_VERSION)"
-    curl http://envy-versions.s3.amazonaws.com/$PYTHON_VERSION.tar.bz2 -s | tar jx &> /dev/null
-    if [[ $? != 0 ]] ; then
-      puts-warn "Requested runtime ($PYTHON_VERSION) was not found."
-      puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
-      exit 1
-    fi
-    mv python .heroku/python
-  bpwatch stop install_python
+# if [ ! "$SKIP_INSTALL" ]; then
+#   bpwatch start install_python
+#     puts-step "Preparing Python runtime ($PYTHON_VERSION)"
+#     curl http://envy-versions.s3.amazonaws.com/$PYTHON_VERSION.tar.bz2 -s | tar jx &> /dev/null
+#     if [[ $? != 0 ]] ; then
+#       puts-warn "Requested runtime ($PYTHON_VERSION) was not found."
+#       puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
+#       exit 1
+#     fi
+#     mv python .heroku/python
+#   bpwatch stop install_python
 
-  # Record for future reference.
-  echo $PYTHON_VERSION > .heroku/python-version
-  FRESH_PYTHON=true
+#   # Record for future reference.
+#   echo $PYTHON_VERSION > .heroku/python-version
+#   FRESH_PYTHON=true
 
-  hash -r
-else
-  puts-step "Using Python runtime ($PYTHON_VERSION)"
-fi
+#   hash -r
+# else
+#   puts-step "Using Python runtime ($PYTHON_VERSION)"
+# fi
 
 # If Pip isn't up to date:
 if [ "$FRESH_PYTHON" ] || [[ ! $(pip --version) == *$PIP_VERSION* ]]; then
